version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - data_platform_net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DWH_USER}"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    environment:
      POSTGRES_PASSWORD: "${DWH_PASSWORD}"
      POSTGRES_USER: "${DWH_USER}"

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.7.19
    volumes:
      - ./dbt:/usr/app
    working_dir: /usr/app
    depends_on:
      - postgres
    networks:
      - data_platform_net
    environment:
      DBT_PROFILES_DIR: /usr/app

volumes:
  postgres-data:

networks:
  data_platform_net:
    external: true
